### ISSUE TITLE
kompilacja

### ISSUE THREAD

**Issue by serfer12** [dataneodev/Arduino#1]
hej mam 2 pytanka :
1) podczas komilacji pojawia się taki błąd ma on jakiś poważny wpływ na program ?  
warning: invalid conversion from 'char' to 'const char*' [-fpermissive]

       addSwitch(switch_pin_no, NORMAL_CLOSE, '\0');

2) jak połączyć dwa sketche na kontaktrony i na czujniki ruchu ? 
albo nawet trzy dodać do tego ds18b20 ?

**Comment by serfer12** [comment]
hej mógłbyś pomóc ? jakoś mi to nie idzie 
https://pastebin.com/N8XBgye4
połączyłem te 2 sketche i w HA wykrywa mi wszystkie kontaktrony i czujniki ruchu jednak czujniki ruchu nie działają nie zmieniają stanu czy to w HA czy serial monitorze

**Comment by dataneodev** [comment]
w sketchu Motion pinMode jest ustawiane na INPUT czyli podajesz do pinu napięcie z czujnika ruchu - ale masy arduino i zasilania czujnika ruchu muszą być połączone ze sobą.

**Comment by dataneodev** [comment]
> hej mam 2 pytanka :
> 
> 1. podczas komilacji pojawia się taki błąd ma on jakiś poważny wpływ na program ?
>    warning: invalid conversion from 'char' to 'const char*' [-fpermissive]
>    ```
>    addSwitch(switch_pin_no, NORMAL_CLOSE, '\0');
>    ```
> 2. jak połączyć dwa sketche na kontaktrony i na czujniki ruchu ?
>    albo nawet trzy dodać do tego ds18b20 ?

1.  trzeba zmienic ' na "
2.  żeby dodać ds18b20  trzeba najpierw ustalić adres czujnika.

**Comment by serfer12** [comment]
Super że się odzywasz dzięki. 
Ja wiem jak mam podłączyć czujniki już mam je spięte na innym sketchu ale te Twoje wyglądają dużo lepiej. 
Udało mi się w domoticzu dodać czujniki ruchu i kontaktrony (połączyłem oba twoje sketche) jednak czujniki ruchu bardzo dziwnie się zachowują albo z opóźnieniem albo robią mi dyskotekę bo się same załączają. Albo jak wejdę w czujnik ruchu to potem muszę długo czekać zanim znowu będę mógł go aktywować
https://pastebin.com/5NjW3GnT

**Comment by dataneodev** [comment]
Przetestowałem sketch MotionManager i jest on ok. 
Źródło twoich problemów (choinka itp) to brak rezystora podciągającego do masy.
Do każdego kabla od czujnika ruchu (w twoim przypadku piny 38-52) w okolicy wpięcia do arduino dodaj rezystor podciągający do masy np. 100K om.

W tym sketchu pinmode jest INPUT czyli arduino mierzy napięcie podane na pin i przy braku takiego rezystora występują własnie takie anomalie (kabel działa jak antena i zbiera wszystkie pola elektromatnetyczne z okolicy).

Podłączanie kabli od czujników bezpośrednio do arduino to zły pomysł, mogę podesłać przykład swojego zabezpieczenie ESD przy użyciu opto-izolatora.

**Comment by serfer12** [comment]
jasne chętnie zobaczę Twoje zabezpiecznie ESD 
dziwne bo na innym sketchu nie mam takich anomalii :) 
Czy w twoim sketchu pin jest ustawiony jako pull_up ?

**Comment by serfer12** [comment]
a jak by dodać tak samo jak jest w kontaktronach debouncera i input_pullup ? 

można czy to coś popsuje ? 

void initPin() {
      if (_motion_pin_no == 0) return;
      pinMode(_motion_pin_no, INPUT_PULLUP);
      _debouncer = Bounce();
      _debouncer.attach(_motion_pin_no);
      _debouncer.interval(5);
      checkmotion(true);

takie coś dodałem ale mi się nie kompiluje wywala błąd    _debouncer = Bounce();

**Comment by serfer12** [comment]
Hej 
Dlaczego zamknąłeś  ? Coś nie tak napisałem ? 
Mógłbyś mi napisać co to za bilblioteka do DS18B20manager bo to zwykła DS18B20 nie działa z Twoim sketchem
